name: account_book_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.1.0+12

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^1.18.0
  firebase_analytics: ^9.1.10
  firebase_auth: ^3.3.20
  firebase_storage: ^10.3.11
  cloud_firestore: ^3.4.8
  hooks_riverpod: ^2.0.2
  flutter_hooks: ^0.18.5+1
  go_router: ^6.0.1
  fluttertoast: ^8.0.9
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  image_picker: ^0.8.6
  image_cropper: ^3.0.1
  webview_flutter: ^3.0.4
  google_sign_in: ^5.4.2
  app_review: ^2.1.2+1
  google_fonts: ^3.0.1
  sensors_plus: ^2.0.1
  sqflite: ^2.2.2
  http: ^0.13.5
  flutter_staggered_grid_view: ^0.6.2
  lottie: ^2.2.0
  path: ^1.8.2
  shared_preferences: ^2.0.16

    
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  freezed: ^2.1.0+1
  json_serializable: ^6.4.0
  flutter_launcher_icons: ^0.11.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/
    - assets/json/

flutter_icons:
  android: true 
  ios: true
