name: account_book_app
description: A new Flutter project.


publish_to: 'none' 


version: 1.1.0+12

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core:
  firebase_analytics:
  firebase_auth:
  firebase_storage:
  cloud_firestore:
  hooks_riverpod: ^2.0.2
  flutter_hooks: ^0.18.5+1
  go_router:
  fluttertoast:
  json_annotation:
  freezed_annotation:
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  qr_flutter:
  qr_code_scanner:
  image_picker:
  image_cropper:
  webview_flutter:
  google_sign_in:
  app_review:
  google_fonts:
  sensors_plus:
  sqflite:
  http:
  flutter_staggered_grid_view:
  lottie:
  path:
  shared_preferences:
  flutter_svg: ^1.1.6
  cached_network_image: 
    
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  auto_route_generator: ^5.0.2
  build_runner: ^2.2.1
  freezed: ^2.1.0+1
  json_serializable: ^6.4.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets\img\png_jpg\splash_icon.png'
  color_dark: '#262626'
  image_dark: 'assets\img\png_jpg\splash_icon.png'
  fullscreen: true
  android_12:
    icon_background_color: '#FFFFFF'
    image: 'assets\img\png_jpg\splash_icon.png'
    icon_background_color_dark: '#262626'
    image_dark: 'assets\img\png_jpg\splash_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/img/svg/
    - assets/img/png_jpg/
    - assets/json/

flutter_icons:
  android: true 
  ios: true
