name: account_book_app
description: A new Flutter project.


publish_to: 'none' 


version: 2.1.0+13

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  firebase_core: ^2.7.0
  firebase_analytics: ^10.1.4
  firebase_auth: ^4.2.9
  firebase_storage: ^11.0.14
  cloud_firestore: ^4.4.3
  hooks_riverpod: ^2.2.0
  flutter_hooks: ^0.18.6
  go_router: ^6.2.0
  fluttertoast: ^8.2.1
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  image_picker: ^0.8.6+3
  image_cropper: ^3.0.1
  webview_flutter: ^4.0.5
  google_sign_in: ^6.0.1
  google_fonts: ^4.0.3
  sqflite: ^2.2.4+1
  http: ^0.13.5 
  lottie: ^2.2.0 
  path: ^1.8.2
  shared_preferences: ^2.0.18
  flutter_svg: ^2.0.0
  cached_network_image: ^3.2.3 
    
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.1
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16

flutter_native_splash:
  color: '#FFFFFF'
  image: 'assets\img\png_jpg\splash_icon.png'
  color_dark: '#262626'
  image_dark: 'assets\img\png_jpg\splash_icon.png'
  fullscreen: true
  android_12:
    icon_background_color: '#FFFFFF'
    image: 'assets\img\png_jpg\splash_icon.png'
    icon_background_color_dark: '#262626'
    image_dark: 'assets\img\png_jpg\splash_icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/img/svg/
    - assets/img/png_jpg/
    - assets/json/

flutter_icons:
  android: true 
  ios: true
